---
- name: Install curl
  apt: name=curl update_cache=yes
  become: yes

- name: Adding GPG key
  shell: 'curl -sSL https://rvm.io/mpapis.asc | gpg --import -'

- name: Install RVM
  shell: 'curl -L https://get.rvm.io | `which bash` -s -- --version {{ rvm_version }}'

- name: Load RVM
  lineinfile: dest='{{ home_directory }}/.bashrc' line='source $HOME/.rvm/scripts/rvm'

- name: Install RVM dependencies
  command: '{{ home_directory }}/.rvm/bin/rvm requirements'
  become: yes
